// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: profiler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_SHOW    Op = 0
	Op_ENABLE  Op = 1
	Op_DISABLE Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "SHOW",
		1: "ENABLE",
		2: "DISABLE",
	}
	Op_value = map[string]int32{
		"SHOW":    0,
		"ENABLE":  1,
		"DISABLE": 2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_profiler_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_profiler_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_profiler_proto_rawDescGZIP(), []int{0}
}

type ProfilerOPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestOp  Op    `protobuf:"varint,1,opt,name=request_op,json=requestOp,proto3,enum=longhorn.grpc.profiler.Op" json:"request_op,omitempty"`
	PortNumber int32 `protobuf:"varint,2,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
}

func (x *ProfilerOPRequest) Reset() {
	*x = ProfilerOPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilerOPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerOPRequest) ProtoMessage() {}

func (x *ProfilerOPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerOPRequest.ProtoReflect.Descriptor instead.
func (*ProfilerOPRequest) Descriptor() ([]byte, []int) {
	return file_profiler_proto_rawDescGZIP(), []int{0}
}

func (x *ProfilerOPRequest) GetRequestOp() Op {
	if x != nil {
		return x.RequestOp
	}
	return Op_SHOW
}

func (x *ProfilerOPRequest) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

type ProfilerOPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfilerAddr string `protobuf:"bytes,1,opt,name=profiler_addr,json=profilerAddr,proto3" json:"profiler_addr,omitempty"`
}

func (x *ProfilerOPResponse) Reset() {
	*x = ProfilerOPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilerOPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerOPResponse) ProtoMessage() {}

func (x *ProfilerOPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerOPResponse.ProtoReflect.Descriptor instead.
func (*ProfilerOPResponse) Descriptor() ([]byte, []int) {
	return file_profiler_proto_rawDescGZIP(), []int{1}
}

func (x *ProfilerOPResponse) GetProfilerAddr() string {
	if x != nil {
		return x.ProfilerAddr
	}
	return ""
}

var File_profiler_proto protoreflect.FileDescriptor

var file_profiler_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x6c, 0x6f, 0x6e, 0x67, 0x68, 0x6f, 0x72, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x72, 0x4f, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x6e, 0x67, 0x68, 0x6f, 0x72, 0x6e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70,
	0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x12, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x72, 0x4f, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x2a, 0x27, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48,
	0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x32, 0x71, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x65, 0x0a, 0x0a, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x72, 0x4f, 0x50, 0x12, 0x29, 0x2e, 0x6c, 0x6f, 0x6e, 0x67, 0x68, 0x6f,
	0x72, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72,
	0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x4f, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6c, 0x6f, 0x6e, 0x67, 0x68, 0x6f, 0x72, 0x6e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x72, 0x4f, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_profiler_proto_rawDescOnce sync.Once
	file_profiler_proto_rawDescData = file_profiler_proto_rawDesc
)

func file_profiler_proto_rawDescGZIP() []byte {
	file_profiler_proto_rawDescOnce.Do(func() {
		file_profiler_proto_rawDescData = protoimpl.X.CompressGZIP(file_profiler_proto_rawDescData)
	})
	return file_profiler_proto_rawDescData
}

var file_profiler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profiler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profiler_proto_goTypes = []interface{}{
	(Op)(0),                    // 0: longhorn.grpc.profiler.Op
	(*ProfilerOPRequest)(nil),  // 1: longhorn.grpc.profiler.ProfilerOPRequest
	(*ProfilerOPResponse)(nil), // 2: longhorn.grpc.profiler.ProfilerOPResponse
}
var file_profiler_proto_depIdxs = []int32{
	0, // 0: longhorn.grpc.profiler.ProfilerOPRequest.request_op:type_name -> longhorn.grpc.profiler.Op
	1, // 1: longhorn.grpc.profiler.Profiler.ProfilerOP:input_type -> longhorn.grpc.profiler.ProfilerOPRequest
	2, // 2: longhorn.grpc.profiler.Profiler.ProfilerOP:output_type -> longhorn.grpc.profiler.ProfilerOPResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profiler_proto_init() }
func file_profiler_proto_init() {
	if File_profiler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profiler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilerOPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profiler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilerOPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profiler_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiler_proto_goTypes,
		DependencyIndexes: file_profiler_proto_depIdxs,
		EnumInfos:         file_profiler_proto_enumTypes,
		MessageInfos:      file_profiler_proto_msgTypes,
	}.Build()
	File_profiler_proto = out.File
	file_profiler_proto_rawDesc = nil
	file_profiler_proto_goTypes = nil
	file_profiler_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfilerClient is the client API for Profiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilerClient interface {
	ProfilerOP(ctx context.Context, in *ProfilerOPRequest, opts ...grpc.CallOption) (*ProfilerOPResponse, error)
}

type profilerClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilerClient(cc grpc.ClientConnInterface) ProfilerClient {
	return &profilerClient{cc}
}

func (c *profilerClient) ProfilerOP(ctx context.Context, in *ProfilerOPRequest, opts ...grpc.CallOption) (*ProfilerOPResponse, error) {
	out := new(ProfilerOPResponse)
	err := c.cc.Invoke(ctx, "/longhorn.grpc.profiler.Profiler/ProfilerOP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilerServer is the server API for Profiler service.
type ProfilerServer interface {
	ProfilerOP(context.Context, *ProfilerOPRequest) (*ProfilerOPResponse, error)
}

// UnimplementedProfilerServer can be embedded to have forward compatible implementations.
type UnimplementedProfilerServer struct {
}

func (*UnimplementedProfilerServer) ProfilerOP(context.Context, *ProfilerOPRequest) (*ProfilerOPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfilerOP not implemented")
}

func RegisterProfilerServer(s *grpc.Server, srv ProfilerServer) {
	s.RegisterService(&_Profiler_serviceDesc, srv)
}

func _Profiler_ProfilerOP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfilerOPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilerServer).ProfilerOP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/longhorn.grpc.profiler.Profiler/ProfilerOP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilerServer).ProfilerOP(ctx, req.(*ProfilerOPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "longhorn.grpc.profiler.Profiler",
	HandlerType: (*ProfilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProfilerOP",
			Handler:    _Profiler_ProfilerOP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profiler.proto",
}
