#!/bin/bash

set -e

cd $(dirname $0)/..

# Copy Google built-in protobuf files
mkdir -p ./proto/google || true
cp -rf /usr/local/include/google ./proto/

# Generate profiler stub files
mkdir -p ./generated/profilerpb || true
protoc -I ./proto -I ./proto/google/protobuf \
  --go_opt=paths=source_relative \
  --go_out=./generated/profilerpb \
  --go-grpc_opt=paths=source_relative \
  --go-grpc_out=./generated/profilerpb \
  ./proto/profiler.proto
